print('===== DESAFIO 01 =====')
nome = input('Qual é o seu nome? ')
print('Olá ', nome, '! Prazer em te conhecer!')
print()
print('===== DESAFIO 02 =====')
print('Digite a data do seu nascimento:')
dia = input('Dia: ')
mes = input('Mes: ')
ano = input('Ano: ')
print('Você nasceu em ', dia, '/', mes, '/', ano, '. Correto?')
print()
print('===== DESAFIO 03 =====, imcompleto -_-')
a = input('1º Termo: ')
b = input('2º Termo: ')
r = a + b
print('A Soma é ', r)

